#!bin/usr/perl

use 5.010;
 
# Initialize a hash
# Assigning an empty list
my %emptyList = ();

# Initialize a hash reference (aka hash_ref or href)
my $hash = {};
$hash{'name'} = 'austin';
$hash{'number'} = 1000;

# Add several key/value pairs to a hash
my %areaCode = ('sf', 415, 'seattle', 206, 'honolulu', 808);

say $hash;
say %hash;
say %areaCode;


my @keys = keys %areaCode;
say "@keys";

my @values = values %areaCode;
say "@values";