#!/usr/bin/perl

use 5.010;

# declare an array to hold a list of numbers using range operator (...)
@nums = 0...10;

# push an element to the end of the array
push @nums, 11;

# push elements to the end of the array
push @nums, 12...15;

say @nums;

# pop the last element from the array
$zero = pop @nums;

say $zero;

# unshift to add element(s) to the beginning of the array
unshift @nums, (-2, -1);

say @nums;

# shift to remove an element at the beginning of the array
shift @nums;
